step-restore-cache: &step-restore-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - v1-dependencies-{{ arch }}

steps-test: &steps-test
  steps:
    - checkout
    - *step-restore-cache
    - run: yarn
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
    - run: yarn test

version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  test-linux-14:
    docker:
      - image: cimg/node:14.21
    <<: *steps-test

workflows:
  version: 2
  test_and_release:
    jobs:
      - test-linux-14


